# http://192.168.99.100/
nginx:
    image: tutum/nginx
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
phpfpm:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./public:/usr/share/nginx/html
database:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin
# http://192.168.99.100:8183/
# Server: database
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - database
  ports:
    - 8183:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: romanpw
    PMA_ARBITRARY: 1
